set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

set_property PACKAGE_PIN AG13 [get_ports uart_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_0_rxd]
set_property PACKAGE_PIN W11 [get_ports uart_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_0_txd]
set_property PACKAGE_PIN AH13 [get_ports {uart_0_txen[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {uart_0_txen[0]}]

# eeprom
## eeprom sda
set_property PACKAGE_PIN W14 [get_ports eeprom_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports eeprom_sda_io]
## eeprom scl
set_property PACKAGE_PIN AB15 [get_ports eeprom_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports eeprom_scl_io]

# unused
## sda
set_property PACKAGE_PIN AA12 [get_ports i2c_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_0_sda_io]
## scl
set_property PACKAGE_PIN Y12 [get_ports i2c_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_0_scl_io]


# ch_0
## sda
set_property PACKAGE_PIN Y8 [get_ports i2c_1_sda_io]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_1_sda_io]
## scl
set_property PACKAGE_PIN W8 [get_ports i2c_1_scl_io]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_1_scl_io]

# ch_1
## sda
set_property PACKAGE_PIN C1 [get_ports i2c_2_sda_io]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_2_sda_io]
## scl
set_property PACKAGE_PIN B1 [get_ports i2c_2_scl_io]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_2_scl_io]

# ch_2
## sda
set_property PACKAGE_PIN V9 [get_ports i2c_3_sda_io]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_3_sda_io]
## scl
set_property PACKAGE_PIN U9 [get_ports i2c_3_scl_io]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_3_scl_io]

# unused
# ch_3
## sda
set_property PACKAGE_PIN C9 [get_ports i2c_4_sda_io]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_4_sda_io]
## scl
set_property PACKAGE_PIN B9 [get_ports i2c_4_scl_io]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_4_scl_io]


# relay_ctrl
set_property -dict {PACKAGE_PIN AG11 IOSTANDARD LVCMOS33} [get_ports {gpio_tri_io[0]}]

#PL_LOCK_LED
set_property -dict {PACKAGE_PIN AF11 IOSTANDARD LVCMOS33} [get_ports {gpio_tri_io[1]}]

# EEPROM WRITE PROTECT
set_property -dict {PACKAGE_PIN AB14 IOSTANDARD LVCMOS33} [get_ports {gpio_tri_io[2]}]

################################################################################################

################################################################################################
create_clock -period 20.000 [get_ports ch0_clkin0_p]
create_clock -period 20.000 [get_ports ch0_clkin1_p]

set_property ODT RTT_48 [get_ports ch0_clkin0_p]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch0_clkin0_p]
set_property PACKAGE_PIN M6 [get_ports ch0_clkin0_p]
set_property PACKAGE_PIN L5 [get_ports ch0_clkin0_n]
set_property ODT RTT_48 [get_ports ch0_clkin0_n]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch0_clkin0_n]

set_property ODT RTT_48 [get_ports {ch0_datain0_p[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain0_p[0]}]
set_property PACKAGE_PIN L1 [get_ports {ch0_datain0_p[0]}]
set_property PACKAGE_PIN K1 [get_ports {ch0_datain0_n[0]}]
set_property ODT RTT_48 [get_ports {ch0_datain0_n[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain0_n[0]}]
set_property ODT RTT_48 [get_ports {ch0_datain0_p[1]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain0_p[1]}]
set_property PACKAGE_PIN J7 [get_ports {ch0_datain0_p[1]}]
set_property PACKAGE_PIN H7 [get_ports {ch0_datain0_n[1]}]
set_property ODT RTT_48 [get_ports {ch0_datain0_n[1]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain0_n[1]}]
set_property ODT RTT_48 [get_ports {ch0_datain0_p[2]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain0_p[2]}]
set_property PACKAGE_PIN M8 [get_ports {ch0_datain0_p[2]}]
set_property PACKAGE_PIN L8 [get_ports {ch0_datain0_n[2]}]
set_property ODT RTT_48 [get_ports {ch0_datain0_n[2]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain0_n[2]}]
set_property ODT RTT_48 [get_ports {ch0_datain0_p[3]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain0_p[3]}]
set_property PACKAGE_PIN R6 [get_ports {ch0_datain0_p[3]}]
set_property PACKAGE_PIN T6 [get_ports {ch0_datain0_n[3]}]
set_property ODT RTT_48 [get_ports {ch0_datain0_n[3]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain0_n[3]}]

set_property ODT RTT_48 [get_ports ch0_clkin1_p]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch0_clkin1_p]
set_property PACKAGE_PIN K4 [get_ports ch0_clkin1_p]
set_property PACKAGE_PIN K3 [get_ports ch0_clkin1_n]
set_property ODT RTT_48 [get_ports ch0_clkin1_n]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch0_clkin1_n]

set_property ODT RTT_48 [get_ports {ch0_datain1_p[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain1_p[0]}]
set_property PACKAGE_PIN P7 [get_ports {ch0_datain1_p[0]}]
set_property PACKAGE_PIN P6 [get_ports {ch0_datain1_n[0]}]
set_property ODT RTT_48 [get_ports {ch0_datain1_n[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain1_n[0]}]
set_property ODT RTT_48 [get_ports {ch0_datain1_p[1]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain1_p[1]}]
set_property PACKAGE_PIN R7 [get_ports {ch0_datain1_p[1]}]
set_property PACKAGE_PIN T7 [get_ports {ch0_datain1_n[1]}]
set_property ODT RTT_48 [get_ports {ch0_datain1_n[1]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain1_n[1]}]
set_property ODT RTT_48 [get_ports {ch0_datain1_p[2]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain1_p[2]}]
set_property PACKAGE_PIN K9 [get_ports {ch0_datain1_p[2]}]
set_property PACKAGE_PIN J9 [get_ports {ch0_datain1_n[2]}]
set_property ODT RTT_48 [get_ports {ch0_datain1_n[2]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain1_n[2]}]
set_property ODT RTT_48 [get_ports {ch0_datain1_p[3]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain1_p[3]}]
set_property PACKAGE_PIN N7 [get_ports {ch0_datain1_p[3]}]
set_property PACKAGE_PIN N6 [get_ports {ch0_datain1_n[3]}]
set_property ODT RTT_48 [get_ports {ch0_datain1_n[3]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch0_datain1_n[3]}]

################################################################################################

create_clock -period 20.000 [get_ports ch1_clkin0_p]
create_clock -period 20.000 [get_ports ch1_clkin1_p]

set_property ODT RTT_48 [get_ports ch1_clkin0_p]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch1_clkin0_p]
set_property PACKAGE_PIN C3 [get_ports ch1_clkin0_p]
set_property PACKAGE_PIN C2 [get_ports ch1_clkin0_n]
set_property ODT RTT_48 [get_ports ch1_clkin0_n]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch1_clkin0_n]

set_property ODT RTT_48 [get_ports {ch1_datain0_p[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain0_p[0]}]
set_property PACKAGE_PIN E4 [get_ports {ch1_datain0_p[0]}]
set_property PACKAGE_PIN E3 [get_ports {ch1_datain0_n[0]}]
set_property ODT RTT_48 [get_ports {ch1_datain0_n[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain0_n[0]}]
set_property ODT RTT_48 [get_ports {ch1_datain0_p[1]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain0_p[1]}]
set_property PACKAGE_PIN E1 [get_ports {ch1_datain0_p[1]}]
set_property PACKAGE_PIN D1 [get_ports {ch1_datain0_n[1]}]
set_property ODT RTT_48 [get_ports {ch1_datain0_n[1]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain0_n[1]}]
set_property ODT RTT_48 [get_ports {ch1_datain0_p[2]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain0_p[2]}]
set_property PACKAGE_PIN C6 [get_ports {ch1_datain0_p[2]}]
set_property PACKAGE_PIN B6 [get_ports {ch1_datain0_n[2]}]
set_property ODT RTT_48 [get_ports {ch1_datain0_n[2]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain0_n[2]}]
set_property ODT RTT_48 [get_ports {ch1_datain0_p[3]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain0_p[3]}]
set_property PACKAGE_PIN B3 [get_ports {ch1_datain0_p[3]}]
set_property PACKAGE_PIN A3 [get_ports {ch1_datain0_n[3]}]
set_property ODT RTT_48 [get_ports {ch1_datain0_n[3]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain0_n[3]}]

set_property ODT RTT_48 [get_ports ch1_clkin1_p]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch1_clkin1_p]
set_property PACKAGE_PIN D4 [get_ports ch1_clkin1_p]
set_property PACKAGE_PIN C4 [get_ports ch1_clkin1_n]
set_property ODT RTT_48 [get_ports ch1_clkin1_n]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch1_clkin1_n]

set_property ODT RTT_48 [get_ports {ch1_datain1_p[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain1_p[0]}]
set_property PACKAGE_PIN G6 [get_ports {ch1_datain1_p[0]}]
set_property PACKAGE_PIN F6 [get_ports {ch1_datain1_n[0]}]
set_property ODT RTT_48 [get_ports {ch1_datain1_n[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain1_n[0]}]
set_property ODT RTT_48 [get_ports {ch1_datain1_p[1]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain1_p[1]}]
set_property PACKAGE_PIN G8 [get_ports {ch1_datain1_p[1]}]
set_property PACKAGE_PIN F7 [get_ports {ch1_datain1_n[1]}]
set_property ODT RTT_48 [get_ports {ch1_datain1_n[1]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain1_n[1]}]
set_property ODT RTT_48 [get_ports {ch1_datain1_p[2]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain1_p[2]}]
set_property PACKAGE_PIN G1 [get_ports {ch1_datain1_p[2]}]
set_property PACKAGE_PIN F1 [get_ports {ch1_datain1_n[2]}]
set_property ODT RTT_48 [get_ports {ch1_datain1_n[2]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain1_n[2]}]
set_property ODT RTT_48 [get_ports {ch1_datain1_p[3]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain1_p[3]}]
set_property PACKAGE_PIN F2 [get_ports {ch1_datain1_p[3]}]
set_property PACKAGE_PIN E2 [get_ports {ch1_datain1_n[3]}]
set_property ODT RTT_48 [get_ports {ch1_datain1_n[3]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch1_datain1_n[3]}]

################################################################################################
create_clock -period 12.000 [get_ports ch2_clkin0_p]
create_clock -period 12.000 [get_ports ch2_clkin1_p]

set_property ODT RTT_48 [get_ports ch2_clkin0_p]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch2_clkin0_p]
set_property PACKAGE_PIN L3 [get_ports ch2_clkin0_p]
set_property PACKAGE_PIN L2 [get_ports ch2_clkin0_n]
set_property ODT RTT_48 [get_ports ch2_clkin0_n]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch2_clkin0_n]

set_property ODT RTT_48 [get_ports {ch2_datain0_p[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain0_p[0]}]
set_property PACKAGE_PIN U8 [get_ports {ch2_datain0_p[0]}]
set_property PACKAGE_PIN V8 [get_ports {ch2_datain0_n[0]}]
set_property ODT RTT_48 [get_ports {ch2_datain0_n[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain0_n[0]}]
set_property ODT RTT_48 [get_ports {ch2_datain0_p[1]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain0_p[1]}]
set_property PACKAGE_PIN J5 [get_ports {ch2_datain0_p[1]}]
set_property PACKAGE_PIN J4 [get_ports {ch2_datain0_n[1]}]
set_property ODT RTT_48 [get_ports {ch2_datain0_n[1]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain0_n[1]}]
set_property ODT RTT_48 [get_ports {ch2_datain0_p[2]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain0_p[2]}]
set_property PACKAGE_PIN J1 [get_ports {ch2_datain0_p[2]}]
set_property PACKAGE_PIN H1 [get_ports {ch2_datain0_n[2]}]
set_property ODT RTT_48 [get_ports {ch2_datain0_n[2]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain0_n[2]}]
set_property ODT RTT_48 [get_ports {ch2_datain0_p[3]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain0_p[3]}]
set_property PACKAGE_PIN H9 [get_ports {ch2_datain0_p[3]}]
set_property PACKAGE_PIN H8 [get_ports {ch2_datain0_n[3]}]
set_property ODT RTT_48 [get_ports {ch2_datain0_n[3]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain0_n[3]}]

set_property ODT RTT_48 [get_ports ch2_clkin1_p]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch2_clkin1_p]
set_property PACKAGE_PIN L7 [get_ports ch2_clkin1_p]
set_property PACKAGE_PIN L6 [get_ports ch2_clkin1_n]
set_property ODT RTT_48 [get_ports ch2_clkin1_n]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch2_clkin1_n]

set_property ODT RTT_48 [get_ports {ch2_datain1_p[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain1_p[0]}]
set_property PACKAGE_PIN K8 [get_ports {ch2_datain1_p[0]}]
set_property PACKAGE_PIN K7 [get_ports {ch2_datain1_n[0]}]
set_property ODT RTT_48 [get_ports {ch2_datain1_n[0]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain1_n[0]}]
set_property ODT RTT_48 [get_ports {ch2_datain1_p[1]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain1_p[1]}]
set_property PACKAGE_PIN J6 [get_ports {ch2_datain1_p[1]}]
set_property PACKAGE_PIN H6 [get_ports {ch2_datain1_n[1]}]
set_property ODT RTT_48 [get_ports {ch2_datain1_n[1]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain1_n[1]}]
set_property ODT RTT_48 [get_ports {ch2_datain1_p[2]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain1_p[2]}]
set_property PACKAGE_PIN N9 [get_ports {ch2_datain1_p[2]}]
set_property PACKAGE_PIN N8 [get_ports {ch2_datain1_n[2]}]
set_property ODT RTT_48 [get_ports {ch2_datain1_n[2]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain1_n[2]}]
set_property ODT RTT_48 [get_ports {ch2_datain1_p[3]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain1_p[3]}]
set_property PACKAGE_PIN K2 [get_ports {ch2_datain1_p[3]}]
set_property PACKAGE_PIN J2 [get_ports {ch2_datain1_n[3]}]
set_property ODT RTT_48 [get_ports {ch2_datain1_n[3]}]
set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch2_datain1_n[3]}]
################################################################################################

################################################################################################
#create_clock -period 20.000 [get_ports ch3_clkin0_p]
#create_clock -period 20.000 [get_ports ch3_clkin1_p]

#set_property ODT RTT_48 [get_ports ch3_clkin0_p]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch3_clkin0_p]
#set_property PACKAGE_PIN D7 [get_ports ch3_clkin0_p]
#set_property PACKAGE_PIN D6 [get_ports ch3_clkin0_n]
#set_property ODT RTT_48 [get_ports ch3_clkin0_n]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch3_clkin0_n]

#set_property ODT RTT_48 [get_ports {ch3_datain0_p[0]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain0_p[0]}]
#set_property PACKAGE_PIN A2 [get_ports {ch3_datain0_p[0]}]
#set_property PACKAGE_PIN A1 [get_ports {ch3_datain0_n[0]}]
#set_property ODT RTT_48 [get_ports {ch3_datain0_n[0]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain0_n[0]}]
#set_property ODT RTT_48 [get_ports {ch3_datain0_p[1]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain0_p[1]}]
#set_property PACKAGE_PIN E9 [get_ports {ch3_datain0_p[1]}]
#set_property PACKAGE_PIN D9 [get_ports {ch3_datain0_n[1]}]
#set_property ODT RTT_48 [get_ports {ch3_datain0_n[1]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain0_n[1]}]
#set_property ODT RTT_48 [get_ports {ch3_datain0_p[2]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain0_p[2]}]
#set_property PACKAGE_PIN G5 [get_ports {ch3_datain0_p[2]}]
#set_property PACKAGE_PIN F5 [get_ports {ch3_datain0_n[2]}]
#set_property ODT RTT_48 [get_ports {ch3_datain0_n[2]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain0_n[2]}]
#set_property ODT RTT_48 [get_ports {ch3_datain0_p[3]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain0_p[3]}]
#set_property PACKAGE_PIN G3 [get_ports {ch3_datain0_p[3]}]
#set_property PACKAGE_PIN F3 [get_ports {ch3_datain0_n[3]}]
#set_property ODT RTT_48 [get_ports {ch3_datain0_n[3]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain0_n[3]}]

#set_property ODT RTT_48 [get_ports ch3_clkin1_p]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch3_clkin1_p]
#set_property PACKAGE_PIN E5 [get_ports ch3_clkin1_p]
#set_property PACKAGE_PIN D5 [get_ports ch3_clkin1_n]
#set_property ODT RTT_48 [get_ports ch3_clkin1_n]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports ch3_clkin1_n]

#set_property ODT RTT_48 [get_ports {ch3_datain1_p[0]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain1_p[0]}]
#set_property PACKAGE_PIN F8 [get_ports {ch3_datain1_p[0]}]
#set_property PACKAGE_PIN E8 [get_ports {ch3_datain1_n[0]}]
#set_property ODT RTT_48 [get_ports {ch3_datain1_n[0]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain1_n[0]}]
#set_property ODT RTT_48 [get_ports {ch3_datain1_p[1]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain1_p[1]}]
#set_property PACKAGE_PIN A7 [get_ports {ch3_datain1_p[1]}]
#set_property PACKAGE_PIN A6 [get_ports {ch3_datain1_n[1]}]
#set_property ODT RTT_48 [get_ports {ch3_datain1_n[1]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain1_n[1]}]
#set_property ODT RTT_48 [get_ports {ch3_datain1_p[2]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain1_p[2]}]
#set_property PACKAGE_PIN C8 [get_ports {ch3_datain1_p[2]}]
#set_property PACKAGE_PIN B8 [get_ports {ch3_datain1_n[2]}]
#set_property ODT RTT_48 [get_ports {ch3_datain1_n[2]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain1_n[2]}]
#set_property ODT RTT_48 [get_ports {ch3_datain1_p[3]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain1_p[3]}]
#set_property PACKAGE_PIN B5 [get_ports {ch3_datain1_p[3]}]
#set_property PACKAGE_PIN A5 [get_ports {ch3_datain1_n[3]}]
#set_property ODT RTT_48 [get_ports {ch3_datain1_n[3]}]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {ch3_datain1_n[3]}]


#set_false_path -from [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_0/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]] -to [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_1/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]]
#set_false_path -from [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_0/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]] -to [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_2/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]]
#set_false_path -from [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_0/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]] -to [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_3/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]]
#set_false_path -from [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_1/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]] -to [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_0/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]]
#set_false_path -from [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_1/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]] -to [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_2/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]]
#set_false_path -from [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_1/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]] -to [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_3/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]]
#set_false_path -from [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_2/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]] -to [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_0/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]]
#set_false_path -from [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_2/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]] -to [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_1/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]]
#set_false_path -from [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_2/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]] -to [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_3/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]]
#set_false_path -from [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_3/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]] -to [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_0/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]]
#set_false_path -from [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_3/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]] -to [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_1/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]]
#set_false_path -from [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_3/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]] -to [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_2/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]]

set_property LOC BITSLICE_CONTROL_X0Y11 [get_cells system_i/lvds4x2_1to7_2/inst/icontrol]
set_property LOC BITSLICE_CONTROL_X0Y12 [get_cells system_i/lvds4x2_1to7_0/inst/icontrol]
set_property LOC BITSLICE_CONTROL_X0Y19 [get_cells system_i/lvds4x2_1to7_1/inst/icontrol]
#set_property LOC BITSLICE_CONTROL_X0Y20 [get_cells system_i/lvds4x2_1to7_3/inst/icontrol]



#set_false_path -from [get_clocks clk_pl_0] -to [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_0/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]]
#set_false_path -from [get_clocks clk_pl_0] -to [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_1/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]]
#set_false_path -from [get_clocks clk_pl_0] -to [get_clocks -of_objects [get_pins system_i/lvds4x2_1to7_2/inst/rx_inst/rx_clkgen/rx_plle2_adv_inst/CLKFBOUT]]

set_clock_groups -asynchronous \
  -group [get_clocks clk_pl_0] \
  -group [get_clocks {px_pllmmcm px_pllmmcm_1 px_pllmmcm_2}]
