###############################################################################
# axis_passthrough_monitor.tcl - BSP/HSI driver generation
#
# Version: 1.1 (must match spirit:version in component.xml and OPTION VERSION in
#               drivers/axis_passthrough_monitor_v1_0/data/axis_passthrough_monitor.mdd)
# Revision date: 2026-05-13
#
# - xdefine_include_file -> xparameters.h (NUM_INSTANCES, DEVICE_ID, S_AXI_LITE base/high)
# - axis_passthrough_monitor_g.c is written here (not xdefine_config_file): HSI's
#   xdefine_config_file uses XPAR_XAXISPASSTHROUGHMONITOR_NUM_INSTANCES and
#   #include "xaxispassthroughmonitor.h", which do not match xparameters.h /
#   axis_passthrough_monitor.h. Same pattern as axis_pixel_compare.tcl.
###############################################################################

# Write axis_passthrough_monitor_g.c next to other driver sources (cwd .../src when HSI runs).
proc axis_passthrough_monitor_write_g_c {drv_handle} {
	if {[catch {set periphs [hsi::utils::get_common_driver_ips $drv_handle]}]} {
		set periphs [xget_sw_iplist_for_driver $drv_handle]
	}
	set filename [file join "src" "axis_passthrough_monitor_g.c"]
	set f [open $filename w]
	puts $f "/*******************************************************************"
	puts $f "* CAUTION: This file is automatically generated by HSI (axis_passthrough_monitor.tcl)."
	puts $f "* DO NOT EDIT."
	puts $f "*"
	puts $f "* Description: axis_passthrough_monitor driver configuration (DeviceId, BaseAddr, HighAddr)."
	puts $f "*******************************************************************/"
	puts $f ""
	puts $f "\#include \"xparameters.h\""
	puts $f "\#include \"axis_passthrough_monitor.h\""
	puts $f ""
	puts $f "/* Configuration table: one entry per axis_passthrough_monitor instance in the design. */"
	puts $f "XAxisPassthroughMonitor_Config XAxisPassthroughMonitor_ConfigTable\[XPAR_AXI_PASSTHROUGH_MONITOR_NUM_INSTANCES\] ="
	puts $f "{"

	set comma ""
	foreach periph $periphs {
		set up [string toupper [get_property NAME $periph]]
		puts $f "${comma}\t{"
		puts $f "\t\tXPAR_${up}_DEVICE_ID,"
		puts $f "\t\tXPAR_${up}_S_AXI_LITE_BASEADDR,"
		puts $f "\t\tXPAR_${up}_S_AXI_LITE_HIGHADDR"
		puts $f "\t}"
		set comma ","
	}

	puts $f "};"
	puts $f ""
	close $f
}

proc generate {drv_handle} {
	xdefine_include_file $drv_handle "xparameters.h" "AXI_PASSTHROUGH_MONITOR" \
		"NUM_INSTANCES" "DEVICE_ID" "C_S_AXI_LITE_BASEADDR" "C_S_AXI_LITE_HIGHADDR"
	axis_passthrough_monitor_write_g_c $drv_handle
}
