
#ifndef AXI_PIXEL_COMPARE_H
#define AXI_PIXEL_COMPARE_H

/******************************************************************************
 * @file axis_pixel_compare.h
 * @brief Register access and BSP config types for axis_pixel_compare.
 *
 * Version: 2.5 (must match spirit:version in component.xml and OPTION VERSION in
 *          drivers/axis_pixel_compare_v1_0/data/axis_pixel_compare.mdd)
 * Revision date: 2026-05-13
 *
 * Revision highlights:
 * - xparameters.h, XAxisPixelCompare_Config, ConfigTable, LookupConfig();
 *   axis_pixel_compare_g.c is generated by data/axis_pixel_compare.tcl (DeviceId,
 *   S00_axi_BaseAddr, IntrId / fabric vector; no HighAddr in config struct).
 * - xil_io.h for Xil_In32 / Xil_Out32.
 * - ROI slv_reg16..19: 0-based inclusive box; reset xe=ye=0xFFFF for full frame.
 *****************************************************************************/

/****************** Include Files ********************/
#include "xil_types.h"
#include "xstatus.h"
#include "xil_io.h"
#include "xparameters.h"

/**
 * BSP-generated configuration table (axis_pixel_compare_g.c, see data/axis_pixel_compare.tcl).
 * IntrId: resolved from xparameters.h — ZynqMP/Versal fabric *_INTR_INTR, Zynq-7000
 * *_IP2INTC_IRPT_INTR, canonical XPAR_FABRIC_AXIS_PIXEL_COMPARE_n_VEC_ID, MicroBlaze INTC
 * *_VEC_ID via name scan, else 0U (e.g. PMU).
 */
typedef struct {
	u16 DeviceId;
	UINTPTR S00_axi_BaseAddr;
	u32 IntrId;
} XAxisPixelCompare_Config;

extern XAxisPixelCompare_Config XAxisPixelCompare_ConfigTable[];

const XAxisPixelCompare_Config *XAxisPixelCompare_LookupConfig(u16 DeviceId);

#define COL 0
#define LINE 4
#define FPS 8
#define STATUS 12
#define INTR_CLEAR 16
#define FPS_TOTAL_CNT 20
#define PIXEL_POINT 24
#define STREAM_IN_DATA 28
#define ERROE_DATA_HOLD 32
#define STREAM_IN_DATA_HOLD 36
#define PIXEL_THRESHOLD 40
#define ERR_COL 44
#define ERR_LINE 48
#define RGB_CNT_PIXEL 52       /* slv_reg13: target RGB for per-frame hit count (read) */
#define RGB_PIXEL_TOTAL 56
#define RGB_NOT_PIXEL 60

/* RGB hit-count region (slv_reg16..19). Lower 16 bits: 0-based inclusive [x_start,x_end] x [y_start,y_end],
 * same indexing as internal col_cnt / line_cnt (see axis_pixel_compare.v). Power-on reset from IP
 * parameters ROI_RST_* (default xe/ye=100 in RTL; use 0xFFFF for full-span ends). Host 1-based: subtract 1 in SW. */
#define ROI_X_START 64
#define ROI_X_END   68
#define ROI_Y_START 72
#define ROI_Y_END   76

#define AXI_LITE_REG_S00_AXI_SLV_REG20_OFFSET 80
#define AXI_LITE_REG_S00_AXI_SLV_REG21_OFFSET 84
#define AXI_LITE_REG_S00_AXI_SLV_REG22_OFFSET 88
#define AXI_LITE_REG_S00_AXI_SLV_REG23_OFFSET 92
#define AXI_LITE_REG_S00_AXI_SLV_REG24_OFFSET 96
#define AXI_LITE_REG_S00_AXI_SLV_REG25_OFFSET 100
#define AXI_LITE_REG_S00_AXI_SLV_REG26_OFFSET 104
#define AXI_LITE_REG_S00_AXI_SLV_REG27_OFFSET 108
#define AXI_LITE_REG_S00_AXI_SLV_REG28_OFFSET 112
#define AXI_LITE_REG_S00_AXI_SLV_REG29_OFFSET 116
#define AXI_LITE_REG_S00_AXI_SLV_REG30_OFFSET 120
#define AXI_LITE_REG_S00_AXI_SLV_REG31_OFFSET 124


/**************************** Type Definitions *****************************/
/**
 *
 * Write a value to a AXI_LITE_REG register. A 32 bit write is performed.
 * If the component is implemented in a smaller width, only the least
 * significant data is written.
 *
 * @param   BaseAddress is the base address of the AXI_LITE_REGdevice.
 * @param   RegOffset is the register offset from the base to write to.
 * @param   Data is the data written to the register.
 *
 * @return  None.
 *
 * @note
 * C-style signature:
 * 	void AXI_LITE_REG_mWriteReg(u32 BaseAddress, unsigned RegOffset, u32 Data)
 *
 */
#define AXI_LITE_REG_mWriteReg(BaseAddress, RegOffset, Data) \
  	Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))

/**
 *
 * Read a value from a AXI_LITE_REG register. A 32 bit read is performed.
 * If the component is implemented in a smaller width, only the least
 * significant data is read from the register. The most significant data
 * will be read as 0.
 *
 * @param   BaseAddress is the base address of the AXI_LITE_REG device.
 * @param   RegOffset is the register offset from the base to write to.
 *
 * @return  Data is the data from the register.
 *
 * @note
 * C-style signature:
 * 	u32 AXI_LITE_REG_mReadReg(u32 BaseAddress, unsigned RegOffset)
 *
 */
#define AXI_LITE_REG_mReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))

/************************** Function Prototypes ****************************/
/**
 *
 * Run a self-test on the driver/device. Note this may be a destructive test if
 * resets of the device are performed.
 *
 * If the hardware system is not built correctly, this function may never
 * return to the caller.
 *
 * @param   baseaddr_p is the base address of the AXI_LITE_REG instance to be worked on.
 *
 * @return
 *
 *    - XST_SUCCESS   if all self-test code passed
 *    - XST_FAILURE   if any self-test code failed
 *
 * @note    Caching must be turned off for this function to work.
 * @note    Self test may fail if data memory and device are not on the same bus.
 *
 */
XStatus AXI_LITE_REG_Reg_SelfTest(void * baseaddr_p);

#endif /* AXI_PIXEL_COMPARE_H */
